id: A93A9F44F
base_file: f2624.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:40:55.888741
  last_modified_at: 2022-05-30 20:40:55.888750
